In [ ]:
# There are two way to convert text to vector:
    # Integer Encoding
    # Embeddings
# Integer encoding in an RNN converts each word/token into a unique integer ID
# A text sequence such as "I love deep learning" to be represented as [1, 2, 3, 4]

In [ ]:
# A tokenizer converts raw text into smaller units called tokens, such as words or subwords
# Tokenization → breaks text into tokens.
# Integer encoding → converts those tokens into numbers.

In [ ]:
# Tokenizer
    # Breaks text into tokens.
# Integer encoding
    # Maps tokens to integer IDs.
# Embedding
    # Converts integer IDs into learned vectors.

In [ ]:
# Code Example

In [1]:
# Import libraries
import numpy as np
import tensorflow
import keras
from keras import Sequential
from keras.layers import Embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences

In [2]:
# Create a doc file
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [3]:
# Preprocess the doc file

In [14]:
# Create tokenizer object
tokenizer = Tokenizer()

In [15]:
# Fit on the docs
tokenizer.fit_on_texts(docs)

In [28]:
# Check word index
vocab_size = len(tokenizer.word_index) + 1

In [19]:
# Counts how many times each word occurs
tokenizer.word_counts
len(tokenizer.word_counts)

17

In [18]:
# how many text documents/sentences were given to the tokenizer
tokenizer.document_count

10

In [20]:
# converts text documents into sequences of integer IDs
sequences=tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [21]:
# pad_sequences() is used to make all text sequences the same length.
# This is very important before giving sequences to an RNN/LSTM/GRU
# neural networks usually expect inputs with the same shape.

sequences = pad_sequences(sequences,padding='post')  # Add 0 at last seqence
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [32]:
# Perform Embedding

# Add embedding layer
model = Sequential()

model.add(
    Embedding(
        input_dim=vocab_size,
        output_dim=2
    )
)

model.build(input_shape=(None, sequences.shape[1]))

model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ (None, 5, 2)           │            36 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 36 (144.00 B)

 Trainable params: 36 (144.00 B)

 Non-trainable params: 0 (0.00 B)

In [33]:
model.compile('adam','accuracy')

In [34]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
[[[ 0.03723636 -0.04632964]
  [ 0.01239327  0.03143431]
  [ 0.02363977 -0.04351262]
  [ 0.02363977 -0.04351262]
  [ 0.02363977 -0.04351262]]

 [[ 0.01239327  0.03143431]
  [ 0.01239327  0.03143431]
  [ 0.02363977 -0.04351262]
  [ 0.02363977 -0.04351262]
  [ 0.02363977 -0.04351262]]

 [[-0.03721254 -0.03359921]
  [-0.03721254 -0.03359921]
  [-0.03365582 -0.01976162]
  [ 0.02363977 -0.04351262]
  [ 0.02363977 -0.04351262]]

 [[ 0.02130506 -0.01538181]
  [-0.00361099 -0.02455546]
  [ 0.02130506 -0.01538181]
  [ 0.01239327  0.03143431]
  [ 0.02130506 -0.01538181]]

 [[ 0.02471944  0.02761852]
  [-0.02668821 -0.03011158]
  [ 0.00895973  0.03548238]
  [-0.0040524   0.00704823]
  [ 0.02363977 -0.04351262]]

 [[-0.02292379 -0.04288879]
  [-0.02292379 -0.04288879]
  [ 0.02363977 -0.04351262]
  [ 0.02363977 -0.04351262]
  [ 0.02363977 -0.04351262]]

 [[-0.03453048  0.04684356]
  [-0.03453048  0.04684356]
  [ 0.02363977 -0.04351262]
  [ 0.02363977 -0.04351262